name: moda_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastcore
    - pandas>=1.5.0,<2.0.0
    - numpy>=1.22.3,<1.23.0
    - matplotlib~=3.5.1  # Adjusted to match dabest's requirement
    - seaborn==0.11.2    # Pin seaborn to a version compatible with dabest
    - scipy>=1.9.3,<2.0.0
    - dabest>=2023.2.14,<2024.0.0
    - scikit-learn
    - statsmodels
    - palmerpenguins
    - jupyter