name: moda_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - fastcore
    - pandas>=2.2.0
    - numpy>=2.1.0
    - matplotlib>=3.10.0
    - seaborn>=0.13.0
    - scipy>=1.15.0
    - dabest==2025.3.27
    - scikit-learn
    - statsmodels
    - palmerpenguins
    - jupyter
    - nbdev

    
