project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "Modern Data Analysis"
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    right:
      - icon: github
        href: https://github.com/acclab/moda
      - icon: twitter
        href: https://twitter.com/estimationstats
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]